// ============================================================
//  TOPICS REGISTRY
//  To add a new topic: add an entry here and create its folder
//  under questions/<topic-id>/
// ============================================================

const TOPICS = [
  {
    id: "arrays",
    name: "Arrays",
    icon: "⚡",
    color: "#00d4ff",
    description: "Most frequent in TCS NQT — two pointers, sliding window, prefix sums",
    questionFiles: [
      "questions/arrays/q1-move-zeroes.js",
      "questions/arrays/q02-second-largest-element.js",
      "questions/arrays/q03-missing-number.js",
      "questions/arrays/q04-two-sum.js",
      "questions/arrays/q05-rotate-array.js",
      "questions/arrays/q06-find-duplicate-number.js",
      "questions/arrays/q07-maximum-subarray-sum.js",
      "questions/arrays/q08-best-time-to-buy-and-sell-stock.js",
      "questions/arrays/q09-majority-element.js",
      "questions/arrays/q10-remove-duplicates-from-sorted-array.js",
      "questions/arrays/q11-leaders-in-array.js",
      "questions/arrays/q12-rearrange-array-alternately.js",
      "questions/arrays/q13-union-of-two-arrays.js",
      "questions/arrays/q14-intersection-of-two-arrays.js",
      "questions/arrays/q15-longest-consecutive-sequence.js",
      "questions/arrays/q16-subarray-with-given-sum.js",
      "questions/arrays/q17-count-pairs-with-given-sum.js",
      "questions/arrays/q18-equilibrium-index.js",
      "questions/arrays/q19-product-of-array-except-self.js",
      "questions/arrays/q20-missing-and-repeating-number.js",
    ]
  },
  {
    id: "strings",
    name: "Strings",
    icon: "🔤",
    color: "#ff6b6b",
    description: "Palindromes, anagrams, frequency maps — expect 1-2 questions",
    questionFiles: [
      "questions/strings/q01-palindrome.js",
      "questions/strings/q02-vowels-consonants.js",
      "questions/strings/q03-anagrams.js",
      "questions/strings/q04-first-non-repeating.js",
      "questions/strings/q05-reverse-words.js",
      "questions/strings/q06-remove-duplicates.js",
      "questions/strings/q07-longest-common-prefix.js",
      "questions/strings/q08-maximum-occurring-character.js",
      "questions/strings/q09-contains-only-digits.js",
      "questions/strings/q10-wildcard-matching.js",
      "questions/strings/q11-toggle-case.js",
      "questions/strings/q12-print-duplicates.js",
      "questions/strings/q13-remove-vowels.js",
      "questions/strings/q14-largest-word.js",
      "questions/strings/q15-string-rotation.js",
      "questions/strings/q16-permutations.js",
      "questions/strings/q17-compress-string.js",
      "questions/strings/q18-remove-blacklist.js",
      "questions/strings/q19-count-words.js",
      "questions/strings/q20-balance-brackets.js",
      "questions/strings/q21-pangram.js",
      "questions/strings/q22-all-substrings.js"
    ]
  },
  {
    id: "sorting",
    name: "Sorting",
    icon: "📊",
    color: "#6bcb77",
    description: "Dutch National Flag, custom comparators, merge sort variants",
    questionFiles: [
      "questions/sorting/q01-dutch-flag.js",
      "questions/sorting/q02-bubble-sort.js",
      "questions/sorting/q03-selection-sort.js",
      "questions/sorting/q04-insertion-sort.js",
      "questions/sorting/q05-sort-by-frequency.js",
      "questions/sorting/q06-merge-sorted-arrays.js",
      "questions/sorting/q07-sort-by-length.js",
      "questions/sorting/q08-sort-by-absolute-diff.js",
      "questions/sorting/q09-ascending-descending.js",
      "questions/sorting/q10-merge-sort.js",
      "questions/sorting/q11-quick-sort.js",
      "questions/sorting/q12-sort-string.js",
      "questions/sorting/q13-bubble-sort-swaps.js",
      "questions/sorting/q14-kth-smallest.js",
      "questions/sorting/q15-case-insensitive-sort.js",
      "questions/sorting/q16-alternating-pos-neg.js",
      "questions/sorting/q17-sort-pairs.js",
      "questions/sorting/q18-min-swaps.js"
    ]
  },
  {
    id: "number-theory",
    name: "Number Theory",
    icon: "🔢",
    color: "#ffd93d",
    description: "Vehicle problems, AP/GP, prime, GCD/LCM — TCS loves word problems",
    questionFiles: [
      "questions/number-theory/q01-armstrong-number.js",
      "questions/number-theory/q02-check-prime.js",
      "questions/number-theory/q03-nth-fibonacci.js",
      "questions/number-theory/q04-reverse-number.js",
      "questions/number-theory/q05-gcd-lcm.js",
      "questions/number-theory/q06-digital-root.js",
      "questions/number-theory/q07-binary-to-decimal.js",
      "questions/number-theory/q08-count-primes.js",
      "questions/number-theory/q09-vehicle-manufacturing.js",
      "questions/number-theory/q10-sum-of-ap.js",
      "questions/number-theory/q11-perfect-number.js",
      "questions/number-theory/q12-strong-number.js",
      "questions/number-theory/q13-automorphic-number.js",
      "questions/number-theory/q14-harshad-number.js",
      "questions/number-theory/q15-leap-year.js",
      "questions/number-theory/q16-goldbach.js",
      "questions/number-theory/q17-prime-factors.js",
      "questions/number-theory/q18-nth-term-mixed-series.js",
      "questions/number-theory/q19-sum-of-gp.js",
      "questions/number-theory/q20-factorial.js",
      "questions/number-theory/q21-power-of-two.js",
      "questions/number-theory/q22-number-system-conversions.js",
      "questions/number-theory/q23-pair-sum-target.js",
      "questions/number-theory/q24-pascal-triangle.js",
      "questions/number-theory/q25-digit-counts.js",
      "questions/number-theory/q26-max-min-digit.js",
      "questions/number-theory/q27-quadratic-roots.js",
      "questions/number-theory/q28-add-fractions.js"
    ]
  },
  {
    id: "dynamic-programming",
    name: "Dynamic Programming",
    icon: "🧩",
    color: "#c77dff",
    description: "Subset sum, knapsack variants — appears in advanced round",
    questionFiles: []
  },
];